export const ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
};

export const permissions = {
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  MANAGE_WORKSPACE_SETTINGS: "MANAGE_WORKSPACE_SETTINGS",
  TRANSFER_OWNERSHIP: "TRANSFER_OWNERSHIP",
  ARCHIVE_WORKSPACE: "ARCHIVE_WORKSPACE",
  VIEW_WORKSPACE_ANALYTICS: "VIEW_WORKSPACE_ANALYTICS",

  ADD_MEMBER: "ADD_MEMBER",
  REMOVE_MEMBER: "REMOVE_MEMBER",
  CHANGE_MEMBER_ROLE: "CHANGE_MEMBER_ROLE",
  ASSIGN_MEMBER_TO_PROJECT: "ASSIGN_MEMBER_TO_PROJECT",
  INVITE_GUEST: "INVITE_GUEST",
  VIEW_MEMBER_LIST: "VIEW_MEMBER_LIST",

  CREATE_PROJECT: "CREATE_PROJECT",
  EDIT_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  ASSIGN_PROJECT_LEAD: "ASSIGN_PROJECT_LEAD",
  ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
  VIEW_PROJECT_ACTIVITY: "VIEW_PROJECT_ACTIVITY",

  CREATE_TASK: "CREATE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  MARK_TASK_COMPLETE: "MARK_TASK_COMPLETE",
  COMMENT_ON_TASK: "COMMENT_ON_TASK",
  VIEW_TASK_HISTORY: "VIEW_TASK_HISTORY",

  EXPORT_DATA: "EXPORT_DATA",
  GENERATE_REPORT: "GENERATE_REPORT",
  INTEGRATE_THIRD_PARTY_APPS: "INTEGRATE_THIRD_PARTY_APPS",

  VIEW_ONLY: "VIEW_ONLY",
};
